// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PadocaGestor.Infrastructure.Database;

#nullable disable

namespace PadocaGestor.Infrastructure.Migrations
{
    [DbContext(typeof(PadocaContext))]
    [Migration("20260412015642_campoContato")]
    partial class campoContato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("cliente_pk");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Fornecedor", b =>
                {
                    b.Property<long>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdFornecedor"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("character varying")
                        .HasColumnName("endereco");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFornecedor")
                        .HasName("fornecedores_pk");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_funcionario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdFuncionario"));

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdFuncionario")
                        .HasName("funcionarios_pk");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Ingrediente", b =>
                {
                    b.Property<long>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ingrediente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdIngrediente"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("IdIngrediente")
                        .HasName("ingrediente_pk");

                    b.ToTable("ingrediente", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdProduto"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<long>("IdIngrediente")
                        .HasColumnType("bigint")
                        .HasColumnName("id_ingrediente");

                    b.Property<decimal>("Markup")
                        .HasColumnType("numeric")
                        .HasColumnName("markup");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_venda");

                    b.Property<int>("TipoPrecificacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_precificacao");

                    b.HasKey("IdProduto")
                        .HasName("produto_pk");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ProdutoPreco", b =>
                {
                    b.Property<long>("IdProdutoPreco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_preco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdProdutoPreco"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_inicio");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<long>("IdFornecedor")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fornecedor");

                    b.Property<long?>("IdProdutoProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto_produto");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("preco");

                    b.Property<decimal>("Rendimento")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("rendimento");

                    b.HasKey("IdProdutoPreco")
                        .HasName("produto_preco_pk");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdProdutoProduto");

                    b.ToTable("produto_preco", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<long>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdEmpresa"));

                    b.Property<decimal>("Markup")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric");

                    b.Property<string>("Preparo")
                        .HasColumnType("character varying")
                        .HasColumnName("preparo");

                    b.Property<decimal?>("Rendimento")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("rendimento");

                    b.Property<int>("TipoPrecificacao")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("receitas_pk");

                    b.ToTable("receitas", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ReceitaVersaoIngrediente", b =>
                {
                    b.Property<long>("IdProduto")
                        .HasColumnType("bigint")
                        .HasColumnName("id_produto");

                    b.Property<long>("IdReceitaVersao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_receita_versao");

                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Unidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidade");

                    b.HasKey("IdProduto", "IdReceitaVersao")
                        .HasName("receita_versao_ingredientes_pk");

                    b.ToTable("receita_versao_ingredientes", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ReceitasVersao", b =>
                {
                    b.Property<long>("IdReceitaVersao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_receita_versao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("IdReceitaVersao"));

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alterado_por");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataVersao")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_versao");

                    b.Property<long?>("IdReceitas")
                        .HasColumnType("bigint")
                        .HasColumnName("id_receitas");

                    b.HasKey("IdReceitaVersao")
                        .HasName("receitas_versao_pk");

                    b.HasIndex("IdReceitas");

                    b.ToTable("receitas_versao", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.UsuarioCliente", b =>
                {
                    b.Property<long>("IdCliente")
                        .HasColumnType("bigint")
                        .HasColumnName("cliente_id");

                    b.Property<string>("IdUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_usuario");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.HasKey("IdCliente", "IdUsuario")
                        .HasName("usuario_cliente_pk");

                    b.HasIndex(new[] { "IdUsuario" }, "usuario_cliente_uq")
                        .IsUnique();

                    b.ToTable("usuario_cliente", (string)null);
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Produto", b =>
                {
                    b.HasOne("PadocaGestor.Infrastructure.Models.Ingrediente", "IdIngredienteNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdIngrediente")
                        .IsRequired()
                        .HasConstraintName("id_ingrediente_foreign_key");

                    b.Navigation("IdIngredienteNavigation");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ProdutoPreco", b =>
                {
                    b.HasOne("PadocaGestor.Infrastructure.Models.Fornecedor", "IdFornecedorNavigation")
                        .WithMany("ProdutoPrecos")
                        .HasForeignKey("IdFornecedor")
                        .IsRequired()
                        .HasConstraintName("id_fornecedor_foreign_key");

                    b.HasOne("PadocaGestor.Infrastructure.Models.Produto", "IdProdutoProdutoNavigation")
                        .WithMany("ProdutoPrecos")
                        .HasForeignKey("IdProdutoProduto")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("produto_fk");

                    b.Navigation("IdFornecedorNavigation");

                    b.Navigation("IdProdutoProdutoNavigation");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ReceitaVersaoIngrediente", b =>
                {
                    b.HasOne("PadocaGestor.Infrastructure.Models.Produto", "IdProdutoNavigation")
                        .WithMany("ReceitaVersaoIngredientes")
                        .HasForeignKey("IdProduto")
                        .IsRequired()
                        .HasConstraintName("id_produto_foreign_key");

                    b.HasOne("PadocaGestor.Infrastructure.Models.ReceitasVersao", "ReceitaVersao")
                        .WithMany("ReceitaVersaoIngredientes")
                        .HasForeignKey("IdProduto")
                        .IsRequired()
                        .HasConstraintName("id_receita_versao_foreign_key");

                    b.Navigation("IdProdutoNavigation");

                    b.Navigation("ReceitaVersao");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ReceitasVersao", b =>
                {
                    b.HasOne("PadocaGestor.Infrastructure.Models.Receita", "IdReceitasNavigation")
                        .WithMany("ReceitasVersaos")
                        .HasForeignKey("IdReceitas")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("receitas_fk");

                    b.Navigation("IdReceitasNavigation");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.UsuarioCliente", b =>
                {
                    b.HasOne("PadocaGestor.Infrastructure.Models.Cliente", "Cliente")
                        .WithMany("UsuarioClientes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("cliente_fk");

                    b.HasOne("PadocaGestor.Infrastructure.Models.Usuario", "Usuario")
                        .WithOne("UsuarioCliente")
                        .HasForeignKey("PadocaGestor.Infrastructure.Models.UsuarioCliente", "IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("usuario_fk");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Cliente", b =>
                {
                    b.Navigation("UsuarioClientes");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Fornecedor", b =>
                {
                    b.Navigation("ProdutoPrecos");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Ingrediente", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Produto", b =>
                {
                    b.Navigation("ProdutoPrecos");

                    b.Navigation("ReceitaVersaoIngredientes");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Receita", b =>
                {
                    b.Navigation("ReceitasVersaos");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.ReceitasVersao", b =>
                {
                    b.Navigation("ReceitaVersaoIngredientes");
                });

            modelBuilder.Entity("PadocaGestor.Infrastructure.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
